// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfpUt6xA9SST-u3ali3mBbimMpjPXjS9k',
    appId: '1:26953062940:web:564cd9e7aa2bb8647b5dd9',
    messagingSenderId: '26953062940',
    projectId: 'notes-blup-project',
    authDomain: 'notes-blup-project.firebaseapp.com',
    storageBucket: 'notes-blup-project.appspot.com',
    measurementId: 'G-ZJZEB4253Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7GVokAKtx1LRpJFyyIGM3hf5KhJzPeQA',
    appId: '1:26953062940:android:33cf96195efeed1f7b5dd9',
    messagingSenderId: '26953062940',
    projectId: 'notes-blup-project',
    storageBucket: 'notes-blup-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2WaOF0mAX8pGs83KYSfL1dHLVZ4rpW40',
    appId: '1:26953062940:ios:ed308b678119cb3c7b5dd9',
    messagingSenderId: '26953062940',
    projectId: 'notes-blup-project',
    storageBucket: 'notes-blup-project.appspot.com',
    iosClientId: '26953062940-st6er76gckkh2u1db2hapc1aegpm774t.apps.googleusercontent.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2WaOF0mAX8pGs83KYSfL1dHLVZ4rpW40',
    appId: '1:26953062940:ios:ed308b678119cb3c7b5dd9',
    messagingSenderId: '26953062940',
    projectId: 'notes-blup-project',
    storageBucket: 'notes-blup-project.appspot.com',
    iosClientId: '26953062940-st6er76gckkh2u1db2hapc1aegpm774t.apps.googleusercontent.com',
    iosBundleId: 'com.example.notes',
  );
}
