name: Flutter CI with WiX Installer

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
    types: 
      - review_requested
      - ready_for_review
      - opened

jobs:
  flutter_build_and_wix:
    name: Build Blup Desktop App and Create WiX Installer
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v1

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'beta'

      - name: Install Dependencies
        run: |
          flutter pub get
          flutter pub add build_runner
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Enable Windows build
        run: flutter config --enable-windows-desktop

      - name: Build Windows App
        run: flutter build windows --release

      - name: Install WiX Toolset
        run: |
          Invoke-WebRequest -Uri 'https://wixtoolset.org/downloads/v3.11.2/wix311.exe' -OutFile 'wix311.exe'
          Start-Process -Wait -FilePath 'wix311.exe' -ArgumentList '/quiet /norestart'
        shell: powershell

      - name: Create WiX Installer
        shell: bash
        env:
          WIX_PATH_CANDLE: "C:/Program Files (x86)/WiX Toolset v3.11/bin/candle.exe"
          WIX_PATH_LIGHT: "C:/Program Files (x86)/WiX Toolset v3.11/bin/light.exe"
        run: |
          mkdir wixout
          "$WIX_PATH_CANDLE" YourInstallerFile.wxs -o wixout/ -ext WixUtilExtension -ext WixUIExtension
          "$WIX_PATH_LIGHT" wixout/*.wixobj -o Installer.msi -ext WixUtilExtension -ext WixUIExtension
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          mv Installer.msi MyApplication-$(date +'%Y-%m-%d')-${git_hash}.msi
          ls
        working-directory: ${{ github.workspace }}

      - name: Upload WiX Installer to S3
        run: aws s3 cp MyApplication-*.msi s3://exeinstallers/
        working-directory: ${{ github.workspace }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-south-1
