name: Dart CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Set up Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.x'

    - name: Check out code
      uses: actions/checkout@v2

    - name: Get dependencies
      run: flutter pub get

    - name: Analyze and format code
      run: flutter analyze && flutter format --set-exit-if-changed lib test

    - name: Run tests
      run: flutter test
