name: Flutter CI

on:
  push:
    branches:
      - main

jobs:
  build-and-release-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        run: |
          curl https://storage.googleapis.com/flutter_infra/releases/stable/windows/flutter_windows_2.10.0-stable.zip -o flutter_sdk.zip
          Expand-Archive -Path .\flutter_sdk.zip -DestinationPath .\flutter
          echo "::add-path::${{ runner.workspace }}\flutter\bin"

      - name: Install project dependencies
        run: flutter pub get

      - name: Generate intermediates
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Enable Windows build
        run: flutter config --enable-windows-desktop

      - name: Build artifacts
        run: flutter build windows --release

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: notes-${{ github.ref_name }}-windows.zip
          directory: build/windows/runner/Release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/windows/runner/Release/notes-${{ github.ref_name }}-windows.zip
