name: Dart CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Install Dart SDK
      run: |
        curl https://storage.googleapis.com/dart-archive/channels/stable/release/2.16.0/sdk/dartsdk-windows-x64-release.zip -o dartsdk.zip
        powershell -command "Expand-Archive -Path dartsdk.zip -DestinationPath dart-sdk"
        echo "DART_HOME=$(pwd)/dart-sdk" >> $GITHUB_ENV

    - name: Set up Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.x'

    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Flutter SDK
      run: flutter pub global activate --source path .

    - name: Get dependencies
      run: flutter pub get

    - name: Analyze and format code
      run: flutter analyze && flutter format --set-exit-if-changed lib test

    - name: Run tests
      run: flutter test
