name: Flutter CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
    types: 
      - review_requested
      - ready_for_review
      - opened

jobs:
  flutter_build:
    name: Build Blup Desktop App 
    runs-on: windows-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'

      - name: Install Dependencies
        run: flutter pub get

      - name: Enable windows build
        run: flutter config --enable-windows-desktop

      - name: Build Windows App
        run: flutter build windows --release

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: Notes-windows.zip
          directory: build/windows/runner/Release
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Replace with your desired AWS region
      
      - name: Upload Executable to S3
        run: aws s3 cp build/windows/runner/Release/ s3://exeinstallers/ --recursive
