name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [review_requested, ready_for_review, opened ]

jobs:
  flutter_build:
    name: Build from Master
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.13.9'
          channel: "stable"

      - name: Install Dependencies
        working-directory: ./
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run widget tests
        run: flutter test

      - name: Build APK
        working-directory: ./
        run: flutter build apk
