name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [review_requested, ready_for_review, opened ]

jobs:
  flutter_build:
    name: Build Blup Desktop App 
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.10.1' 
          channel: "stable"

      - name: Install Dependencies
        working-directory: ./
        run: flutter pub get


      - name: Build Windows App
        working-directory: ./
        run: flutter build windows
